spring.application.name=aulaProjeto
server.port=${PORT:8080}

spring.datasource.url=${DB_URL} --- IGNORE ---
spring.datasource.username=${DB_USER} --- IGNORE ---
spring.datasource.password=${DB_PASSWORD} --- IGNORE ---
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
