spring.application.name=aulaProjeto
server.port=${PORT:8080}

# Conexão com PostgreSQL do Render — fallback já contém os valores reais
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d8pkhp9194ac739drs3g-a:5432/bancorender_nay7}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bancorender_nay7_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:riXSJxaynfjwONSVCUwIFaOU9pyrVLFW}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
